org: henningwold
app: kirc-endpoint
service: kirc-endpoint

frameworkVersion: '2'

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam: 
    role:
      statements:
        - Effect: Allow
          Action: sqs:SendMessage
          Resource: arn:aws:sqs:eu-central-1:030483651510:message_queue.fifo
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:BatchGetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:ConditionCheckItem
          Resource: arn:aws:dynamodb:eu-central-1:030483651510:table/kirc

functions:
  send-message:
    environment: 
      QUEUE_URL: https://sqs.eu-central-1.amazonaws.com/030483651510/message_queue.fifo
    handler: endpoint.send
    events:
      - http:
          path: /messages
          method: post
  get-messages:
    environment:
      TABLE_NAME: kirc
    handler: endpoint.getMessages
    events:
      - http:
          path: /messages
          method: get
