org: kirckurs
app: gruppe2-endpoint
service: gruppe2-endpoint

frameworkVersion: '2'

provider:
  name: aws
  region: "eu-central-1"
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:BatchGetItem
            - dynamodb:Query
          Resource: arn:aws:dynamodb:eu-central-1:030483651510:table/kirc

functions:
  get-messages:
    handler: dynamodb.getMessage
    events:
      - http:
          path: /messages
          method: get
